spring:
  profiles:
    active: dev
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never

logging:
  level:
    org.hibernate.SQL: debug
    com.safeye.backend: trace

vlm:
  server:
    url: http://localhost:8100